services:
  - type: web
    name: campus-search-backend
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
